<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ISJ6KQ9V" failures="1" tests="1" name="Default test" time="3.859" errors="0" timestamp="2025-02-10T11:51:29 CST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="3.538">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at apiClasses.UserApi.verifyStatusCode(UserApi.java:125)
at stepDefinition.CrudStepDefinition.user_gets_valid_response_body_for_all(CrudStepDefinition.java:32)
at âœ½.user gets valid response body for all(file:///C:/Users/sridh/Desktop/vidhya/API/api_boot/src/test/resources/feature/crudfile.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
